# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('loan_amount', models.FloatField(default=0.0)),
                ('loan_balance', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Dormant', 'Dormant'), ('Blocked', 'Blocked')], default='Pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Mpesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('national_id', models.CharField(default=12345678, max_length=8)),
                ('phone_no', models.CharField(default=254712345678, max_length=12)),
                ('email', models.EmailField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Dormant', 'Dormant'), ('Blocked', 'Blocked')], default='Pending', max_length=15)),
                ('loan_limit', models.FloatField(default=200.0)),
                ('residence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='the loan applicant'),
        ),
    ]
