# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_device_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mpesa',
        ),
    ]
