# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_mpesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Loan Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField(default=0.0)),
                ('reference', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Ok', 'Active'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=15)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Loan', verbose_name='Loan Settlement')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Loan Applicant')),
            ],
        ),
    ]
