# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_activation_settlement_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=254712345678, max_length=15, unique=True),
        ),
    ]
