# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20171029_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='app.User', verbose_name='Loan Applicant'),
        ),
    ]
