# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171029_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='status',
            field=models.CharField(choices=[('Ok', 'Ok'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Settled', 'Settled'), ('Blocked', 'Blocked')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='status',
            field=models.CharField(choices=[('Ok', 'Ok'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='+254712345678', max_length=15, unique=True),
        ),
    ]
