# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20171114_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Loan', verbose_name='Loan'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='Loan Applicant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.BigIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='0712345678', max_length=15, unique=True),
        ),
    ]
